version: '3.5'

# Networks
networks:
  yii2-gb-network:
    name: yii2-gb-network
    driver: bridge

# Services
services:
  # nginx service
  nginx:
    image: nginx:1.23.3
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${PROJECT_PORT}:80
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/${PROJECT_NAME}:rw
      #      - ./.docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:rw
      #      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./.docker/nginx/${PROJECT_NAME}.conf:/etc/nginx/conf.d/${PROJECT_NAME}.conf:rw
      - ./.docker/nginx/log:/var/log/nginx
    depends_on:
      - app
    networks:
      - yii2-gb-network
  # app service
  # При первой настройке обновляем composer.
  # 1. docker container exec -it php-fpm /bin/bash
  # 2. composer self-update && composer update && composer cc && composer validate
  app:
    user: www-data
    build:
      context: .docker/app/
      args:
        context: dev
        project_name: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}_app
    working_dir: /var/www/${PROJECT_NAME}
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/${PROJECT_NAME}
    depends_on:
      - db
    networks:
      - yii2-gb-network
  # db service
  db:
    image: mysql:8
    container_name: ${PROJECT_NAME}_db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${PROJECT_NAME}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
#      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/99-overrides.cnf
      - ./.docker/mysql/db:/var/lib/mysql
      - ./.docker/mysql/bak/:/bak
#      - ./.docker/mysql/dumps/${DUMP_FILE}:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - yii2-gb-network