<?php

namespace app\base;

use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

abstract class BaseController extends Controller
{
    /**
     * @param $action
     * @return bool
     * @throws BadRequestHttpException
     */
    public function beforeAction($action): bool
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @param $action
     * @param $result
     * @return mixed
     */
    public function afterAction($action, $result)
    {
        $session = Yii::$app->session;
        if (Yii::$app->request->absoluteUrl) {
            $session->set('previousPage', Yii::$app->request->absoluteUrl);
        }
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}