<?php

namespace app\base;

use Yii;
use yii\web\Controller;

abstract class BaseController extends Controller
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $session = Yii::$app->session;
        if (Yii::$app->request->absoluteUrl) {
            $session->set('previousPage', Yii::$app->request->absoluteUrl);
        }
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}